name: Validate

on:
  pull_request:
  push:

env:
  GO111MODULE: on

jobs:
  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: golangci-lint

  GolangCI-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2

  Vet:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run vet
        run: go vet

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: go test -v -cover -race
